### ISSUE TITLE
"Alignment broke with some reads" and "No disjointigs were assembled"

### ISSUE THREAD

**Issue by mjacksonhill** [Wenfei-Xian/TIPP#1]
Hello! Thank you for making this tool; as I only have long-read data for my genomes, this is one of the few accessible ways to try and assemble my organellar genomes. I am running TIPP_plastid using singularity on a SLURM cluster. I am using about 46gb of total reads and I am writing to get some clarification on some of the error messages I am seeing. The test data set with Arabidopsis works correctly.

I am seeing in the output log that my assembly is finished:

```
[2024-10-04 10:09:58] INFO: Final assembly: /work/wenglab/playground/matthew/tp/Tp_combined_reads.fastq.gz.organelle/Tp_combined_reads.fastq.gz.chloroplast.fasta.filter.800.round1.fasta.chloroplast.flye/assembly.fasta
Chloroplast genome with inverted repeats found
```

But immediately after...

```
GraphAligner bioconda 1.0.19-
GraphAligner bioconda 1.0.19-
Load graph from Tp_combined_reads.fastq.gz.organelle/Tp_combined_reads.fastq.gz.chloroplast.fasta.filter.800.round1.organelle.chloroplast.gfa
Build alignment graph
Build minimizer seeder from the graph
Minimizer seeds, length 15, window size 20, density 10
Seed cluster size 1
Extend up to 5 seed clusters
Alignment bandwidth 10
Clip alignment ends with identity < 90%
X-drop DP score cutoff 50000
Backtrace from 10 highest scoring local maxima per cluster
write alignments to Tp_combined_reads.fastq.gz.organelle/Tp_combined_reads.fastq.gz.chloroplast.fasta.graphaligner.chloroplast.gfa.gaf
Align
src/GraphAlignerBitvectorCommon.h:560: Assertion 'traceEnd >= traceStart' failed. Read: m54312U_210611_122919/115212955/ccs. Seed: 0+,0,0,0
Alignment finished
Input reads: 61780 (954120789bp)
Seeds found: 3684802
Seeds extended: 274777
Reads with a seed: 58748 (906791088bp)
Reads with an alignment: 58747 (18345616bp)
Alignments: 536029 (18560074bp) (30701 additional alignments discarded)
End-to-end alignments: 0 (0bp)
Alignment broke with some reads. Look at stderr output.
```

Does this mean an assembly was produced, but that its topology is not fully resolved? I notice in particular the error:

```
Align
src/GraphAlignerBitvectorCommon.h:560: Assertion 'traceEnd >= traceStart' failed. Read: m54312U_210611_122919/115212955/ccs. Seed: 0+,0,0,0
Alignment finished
```

The mitochondrial genome does not finish:

```
###TIPP_plastid for Mitochondrion start:
File Median Count: 2564
[2024-10-04 10:15:11] INFO: Starting Flye 2.9.4-b1799
[2024-10-04 10:15:11] INFO: >>>STAGE: configure
[2024-10-04 10:15:11] INFO: Configuring run
[2024-10-04 10:15:13] INFO: Total read length: 677742490
[2024-10-04 10:15:13] INFO: Reads N50/N90: 15449 / 11372
[2024-10-04 10:15:13] INFO: Minimum overlap set to 10000
[2024-10-04 10:15:13] INFO: >>>STAGE: assembly
[2024-10-04 10:15:13] INFO: Assembling disjointigs
[2024-10-04 10:15:13] INFO: Reading sequences
[2024-10-04 10:15:17] INFO: Building minimizer index
[2024-10-04 10:15:17] INFO: Pre-calculating index storage
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% 
[2024-10-04 10:15:22] INFO: Filling index
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% 
[2024-10-04 10:17:32] INFO: Extending reads
[2024-10-04 11:11:01] INFO: Overlap-based coverage: 1702
[2024-10-04 11:11:01] INFO: Median overlap divergence: 0.000891884
0% 100% 
[2024-10-04 11:43:49] INFO: Assembled 0 disjointigs
[2024-10-04 11:43:49] INFO: Generating sequence
[2024-10-04 11:43:49] INFO: Filtering contained disjointigs
[2024-10-04 11:43:49] INFO: Contained seqs: 0
[2024-10-04 11:43:50] ERROR: No disjointigs were assembled - please check if the read type and genome size parameters are correct
[2024-10-04 11:43:50] ERROR: Pipeline aborted
```

Please see attached the run log and both flye logs.

[overall.log](https://github.com/user-attachments/files/17264249/overall.log)
[chloro_flye.log](https://github.com/user-attachments/files/17264250/chloro_flye.log)
[mito_flye.log](https://github.com/user-attachments/files/17264251/mito_flye.log)

Is there anything I can do to resolve these issues?

**Comment by Wenfei-Xian** [comment]
Hi Matthew,

According to the log, you've successfully assembled the chloroplast genome (the log from Graphaligner shouldn't affect the results), but the pipeline failed to generate the mitochondrial genome.

I recommend downsampling the input dataset to 2-4x read coverage for running the pipeline. The log shows approximately 677 Mb of mitochondrial reads, which, for a mitochondrial genome of around 500 kb, results in a coverage of 1200x. Such high coverage may negatively impact Flye's performance.

Let me know how you'd like to proceed.

Best,
Wenfei

**Comment by mjacksonhill** [comment]
Hi Wenfei, 

Thanks so much for this advice. I see currently automatic downsampling within the script is only enabled for chloroplast, though there is a commented section in the mitochondrial part of the script that would implement downsampling with the variables `$round_cutoff_mito` and `$reads_num_m`.

Would defining these variables and uncommenting that section work to implement automatic random downsampling, or should I just downsample the raw reads at the very beginning?

Additionally, it looks like mode 'organelle' always runs both chloroplast and mitochondrial assembly.  Is there a way to reuse completed chloroplast results to save time? I can probably edit the script to accomplish this, but let me know if there is a reason not to do that.

**Comment by mjacksonhill** [comment]
I implemented downsampling rounds with the same code used earlier for the chloroplast run and it seems to have worked successfully! However, I am not sure what criteria to check the mitochondrial assembly graph for in order to determine successful assembly. I tried using the same criterion as the no-IR chloroplast, as I wasn't yet familiar with .gfa file format:

```
open my$mito_assem,"$fastq_name.$organelle/$fastq_name.mitochondrial.filter.$reads_num_m.round$round.flye/assembly_graph.gfa" or die "Can't open $fastq_name.$organelle/$fastq_name.mitochondrial.filter.$reads_num_m.round$round.flye/assembly_graph.gfa";
my%hash_gfa;
while(<$mito_assem>){
	chomp;
	if($_=~m/^L/){
		my@linkage=split /\t/,$_;
		$hash_gfa{$linkage[1]}+=1;
		$hash_gfa{$linkage[3]}+=1;
	}
}
		
my $number_edge = keys %hash_gfa;
if ($number_edge == 1) {
		$found=1;
		$found_round=$round;
		last;
}
```

This just led the script to run all iterations, never setting `$found = 1`. 
Each final assembly has very slightly different statistics; would raising the number of subsampled reads help with this? I am now also wondering about the 800 reads used to determine my chloroplast results.

I have also implemented a very rough solution to skipping an already-completed chloroplast assembly. I have attached my WIP script and log file :) perhaps when I have some time later I can submit a PR.

[run_log.txt](https://github.com/user-attachments/files/17276177/run_log.txt)
[TIPP_plastid.v2.1.pl.txt](https://github.com/user-attachments/files/17276178/TIPP_plastid.v2.1.pl.txt)

**Comment by Wenfei-Xian** [comment]
Hi Matthew,

The reason why downsampling for the mitochondrial genome is commented out is that the size of plant mitochondrial genomes varies significantly, making it difficult to define a fixed downsampling value. It's recommended to input already downsampled data, which will also help speed up the pipeline since TIARA can be time-consuming when more reads.

To assemble only the chloroplast genome, you can use the -g chloroplast option.

The structure of the chloroplast genome is conserved, typically either containing or lacking an inverted repeat. In contrast, mitochondrial genome structures are more diverse, and automatic graph checking is still not available, so manual visual inspection is necessary. You can input the GFA file into Bandage (https://github.com/rrwick/Bandage) or Bandage-NG (https://github.com/asl/BandageNG) for visualization. 

Best,
Wenfei

**Comment by mjacksonhill** [comment]
Thank you for the resources! Yes, I am realizing now that of the two organellar genomes, the chloroplast is the "easy" one to assemble, hahaha. It seems like the gold standard for mitochondrial assembly right now is short + long read assembly with something like unicycler... probably out of scope for my project for now.

Thanks for all your help!
